const asset = (path) => `${import.meta.env.BASE_URL}assets/${path}`;

export const THEMES = {
  lacquer: {
    id: "lacquer",
    label: "LACQUER",
    background: asset("themes/lacquer-field.png"),
    sprites: asset("bodies/pearl-sprites.png"),
    brush: null,
    paper: "#070706",
    ink: "#c49b52",
    muted: "rgba(196, 155, 82, 0.42)",
    faint: "rgba(196, 155, 82, 0.12)",
    observer: "rgba(220, 179, 100, 0.64)",
    coral: "#d36b4f",
    cyan: "#7eb6cc",
    spriteMode: "pearl",
    orbitMode: "gold",
  },
  white: {
    id: "white",
    label: "WHITE TIME",
    background: asset("themes/white-field.png"),
    sprites: asset("bodies/pearl-sprites.png"),
    brush: null,
    paper: "#f7f5f0",
    ink: "#242625",
    muted: "rgba(60, 62, 60, 0.34)",
    faint: "rgba(70, 72, 70, 0.12)",
    observer: "rgba(55, 57, 55, 0.34)",
    coral: "#d98e78",
    cyan: "#76b9c1",
    spriteMode: "pearl",
    orbitMode: "emboss",
  },
  sumi: {
    id: "sumi",
    label: "SUMI",
    background: asset("themes/sumi-field.png"),
    sprites: asset("bodies/sumi-sprites.png"),
    brush: asset("textures/sumi-brushes-v2.png"),
    paper: "#f3efe5",
    ink: "#191a18",
    muted: "rgba(25, 26, 24, 0.42)",
    faint: "rgba(25, 26, 24, 0.11)",
    observer: "rgba(25, 26, 24, 0.4)",
    coral: "#cf674d",
    cyan: "#5da9c4",
    spriteMode: "sumi",
    orbitMode: "ink",
  },
};

export const THEME_ORDER = ["lacquer", "white", "sumi"];
